spring:
    application:
      name: Phone
    datasource:
      username: root
      password: 137141
      url: jdbc:mysql://127.0.0.1:3306/zpx?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
      driver-class-name: com.mysql.cj.jdbc.Driver
