spring:
    application:
      name: Phone
    datasource:
      username: root
      password: 137141
      url: jdbc:mysql://154.17.235.47:3306/zpx?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
      driver-class-name: com.mysql.cj.jdbc.Driver
    rabbitmq:
      host: 192.168.1.53
      port: 32330
      username: admin
      password: y14YowJOhRMyGCFY
    #去除tomcat上传文件大小限制
    servlet:
      multipart:
        enabled: true
        max-file-size: 500MB
        max-request-size: 600MB
#配置个人参数
zpx:
  picurl: "123"
